[build]
command = "npm run build"
output_dir = "dist"

[env.production]
name = "nomash-library"

[env.preview]
name = "nomash-library-preview"

[build.upload]
format = "directory"

# Cloudflare Pages specific configuration
pages_build_output_dir = "dist"
